name: great_places
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.5.3
  image_picker: ^1.0.8
  location: ^6.0.2
  path: ^1.8.3
  path_provider: ^2.1.3
  provider: ^6.1.2
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
